### ISSUE TITLE
Link object to the scene

### ISSUE THREAD

**Issue by b4zz4** [tin2tin/scene_strip_tools#1]
I still didn't write it, but I think it goes in tone with the tool and blender has several steps to take this.

`bpy.ops.object.make_links_scene()`

![2021-06-25_00-41_24](https://user-images.githubusercontent.com/643833/123367101-c2aa3780-d54f-11eb-898b-07968f9f7659.jpg)

**Comment by tin2tin** [comment]
I'm not sure I understand? Could you explain a bit more what problem you wan to solve and how you want to solve it?
(If you want to make a scene selector, then the outliner already have a "list scenes" mode. I use it in this tutorial:   https://youtube.com/watch?v=g1W7LHOhBx4 ).

**Comment by b4zz4** [comment]
Yeah, I'm sorry, my graph wasn't very enlightening.

When you work with several scenes and want to repeat objects, link them to the scene.

I would like a shortcut and able this plugin could have a link for that.
