### ISSUE TITLE
ERROR: Addon not installing on Blender 3.x series

### ISSUE THREAD

**Issue by 3dcinetv** [tin2tin/scene_strip_tools#3]
I've tried this addon up until Blender version 2.9x.
On Blender 3, when I install it, the addon simply doesn't appear. I have the option to check mark it on the addon list, but it doesn't show on the UI.

**Comment by tin2tin** [comment]
Just download and install this: https://github.com/tin2tin/scene_strip_tools/raw/master/scene_strip_tools.py

And access it in the vse sidebar.

**Comment by 3dcinetv** [comment]
Awesome. Both plugins work now. Thanks.
