### ISSUE TITLE
Issue enabling in blender 3.5

### ISSUE THREAD

**Issue by anajenna** [tin2tin/scene_strip_tools#4]
When I try to enable it, I get this error message.

RuntimeError: Error: Registering operator class:'SEQUENCER_OT_scene_change', bl idname 'sequencer.change_scene' could not be unregistered

If I understand correctly, this is a new issue for certain add-ons in Blender 3.5. [https://b3d.interplanety.org/en/overriding-base-operators-in-blender-3-5-python-api-is-disabled/](url)

Is there a way around this issue? 

P.S. -  Thank you for creating the Blender screenwriter add-on.

**Comment by tin2tin** [comment]
You could try doing a find and replace on "change_scene" to simply call it something else, and let me know how it goes. 

Surprised that this old add-on is still in use. Thank you.

**Comment by anajenna** [comment]
Thank you! I did what you said and replaced all instances of change_scene and scene_change with something_something, and that did the trick. I don’t know much about coding and thought I couldn’t take your advice, but it all worked out. 

This is the new file. 

[scene_strip_tools.zip](https://github.com/tin2tin/scene_strip_tools/files/11437964/scene_strip_tools.zip)

**Comment by tin2tin** [comment]
I updated the add-on to fix this problem. Thank you. And I added "Linked Scenes" as intermediate scenes, so the VSE can now preview and render strips referencing the same scene.
